"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

import { GlobalContextProvider } from "./context/store";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {



  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          <Navbar />
          {children}
          <Footer />
        </GlobalContextProvider>
      </body>
    </html>
  );

  /* if( path === '/dashboard/journal'){
      return (
        <html lang="en">
       <body     className={inter.className}    >
            <GlobalContextProvider>
           
             
              {children}
            
          
            </GlobalContextProvider>
            </body>  
           
        </html>
      )
    }else{

      return (
        <html lang="en">
          <body className={inter.className}>
            <GlobalContextProvider>
            <Navbar/>
              {children}
              <Footer/>
            </GlobalContextProvider>
           
            </body>
        </html>
      )

    }*/
}
